### ISSUE TITLE
Docker-compose.yml error

### ISSUE THREAD

**Issue by tunisiano187** [colloqi/pisignage-server#124]
Hello,
When trying docker-compose up -d, it gives me this

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for volumes: 'media'
Unsupported config option for services: 'pisignage-server'
```
Can you tell me what am i missing?

**Comment by nachochip** [comment]
I had same issue.  I found that by adding         version: '3'
to the top of the yml file it corrects everything.

**Comment by fabian-technocite** [comment]
as this issue is solved, you can close this ticket, thanks
