### ISSUE TITLE
PiSignage-server on Synology Nas Docker

### ISSUE THREAD

**Issue by pidiman** [colloqi/pisignage-server#144]
Hello boys. I'm trying to install a pisignage server on synology nas ds220 + in the docker. Have any of you done this before?

I downloaded this image: https://registry.hub.docker.com/r/pisignage/pisignage-server/

![image](https://user-images.githubusercontent.com/25770225/156755240-aa34c95a-0ddb-4b80-904b-61296cff943d.png)

Port : 3000

![image](https://user-images.githubusercontent.com/25770225/156755524-3c6d71bd-eab2-4f7f-ba90-10b16a1e42b0.png)

I installed mongo image https://registry.hub.docker.com/r/tutum/mongodb/

The application works, but mongo still reports an error:

[conn16] assertion 13 not authorized for query on pisignage-server-dev.settings ns:pisignage-server-dev.settings query:{}
[conn16]  ntoskip:0 ntoreturn:-1

I didn't find anything in the issues or on Google.
Can you help me? 

Thanks a lot!

**Comment by pidiman** [comment]
And I can't change the username at pisignage.com .. after pressing Save I still have LOCAL..

**Comment by hitesh83** [comment]
mongo you are using is too old, try from official image 
https://registry.hub.docker.com/_/mongo

**Comment by pidiman** [comment]
Thanks @hitesh83
