### ISSUE TITLE
Advertisement playlists: how does 'only on selected days' work?

### ISSUE THREAD

**Issue by Luke1982** [colloqi/pisignage-server#150]
![afbeelding](https://user-images.githubusercontent.com/8875222/168760531-0300b47a-afa0-436d-8f40-dedf4038427a.png)

If I set up my playlist like above: will this run only on Fridays? Or do I need to enable all the days of the month in order to 'unlock' Fridays?

**Comment by hitesh83** [comment]
Yes, the playlist will run on the selected date and in the selected time band only.

**Comment by Luke1982** [comment]
I don't understand you: will it play on the selected day (Friday in this example) if I don't select anything in 'Day(s) of month'? Or do I need to enable 'Day(s) of month' **and** Friday in 'Week Day(s)' to make sure it plays on Fridays?

**Comment by hitesh83** [comment]
if you select only Friday, playlist will be active only on friday, you dont have to select anything else. 
As per screenshot , playlist will be active on every friday from 18hrs  to 23.59 hr. (6pm to 11.59pm)

**Comment by Luke1982** [comment]
Nice, thanks!
