### ISSUE TITLE
How to prevent Raspberry to send "TV on" HDMI signal

### ISSUE THREAD

**Issue by Luke1982** [colloqi/pisignage-server#177]
How can I prevent PiSignage to send a 'TV on' signal? I get reports from people that notice that every time the loop re-starts (e.g. all assets have been played and the loop re-starts), the TV('s) turn on.

**Comment by AbhijithBn** [comment]
Hi @Luke1982 

To have finer control over TV_OFF and TV_OFF make sure you schedule the TV_OFF playlist and ensure no other playlist is scheduled during the TV_OFF -> TV_ON time schedule.
