### ISSUE TITLE
New android app does not work on opensource server

### ISSUE THREAD

**Issue by Narrowcastingscherm** [colloqi/pisignage-server#178]
For a long time i have some opensource server, but the new android app or google chrome app does not work on my server. It says that it is connected, however no content is showing in the app and on the server itself i dont see the player come in. The old google app (extension) is working. can someone help me on the way how to fix this i realy have no idea where to look

**Comment by hitesh83** [comment]
Android app and the new Chrome app are Progressive Web Apps
support for PWA is not there in open-source servers,
might be next update is coming with support.

**Comment by colloqi** [comment]
New Android app should work with settings. Progressive web app will work only with https open source server as mixing https and http is not allowed

**Comment by bigpappa456** [comment]
Little update, in the docker version i can connect to the interface with my android player. I cannot connect with google chromecast android tv to my own env. This has reverse proxy and https, i cannot see any player come in. If i use a raspberry pi it works. Has anyone got an idea what this can be or how to fix this. env is on the latest release of ubuntu and pisinage server

**Comment by AbhijithBn** [comment]
@bigpappa456 
Did you change the server from default (https://pisignage.com) to your server address?
Reference: https://help.pisignage.com/hc/en-us/articles/14265849341081-Change-server-in-PiSignage-Android-2-0
