### ISSUE TITLE
Error : Range not satisfiable

### ISSUE THREAD

**Issue by Rworld-Ravi** [colloqi/pisignage-server#18]
in releases 0.9.0 and later , After deploy only first slide keeps repeating /flashing until the node server is closed at command line. 

![screen shot 2016-01-02 at 5 43 25 pm](https://cloud.githubusercontent.com/assets/11404934/12078826/d6868772-b246-11e5-9c65-d8d9d97b5011.png)

**Comment by Rworld-Ravi** [comment]
I traced out to some extent in the logs and messages. and found a code line about to ignore this error. as shown in the below picture
![screen shot 2016-01-03 at 7 16 10 pm](https://cloud.githubusercontent.com/assets/11404934/12078999/a2f8f266-b24e-11e5-8396-872545161a6c.png)

in the second if statement , before editing the code there was a "~" NOT operator before "err.message.indexof(xxxxxxxx)". i removed NOT operator and voila, everything worked fine :+1:

**Comment by Rworld-Ravi** [comment]
After some successful deploys the problem landed again. Any leads??

**Comment by colloqi** [comment]
unable to simulate, can you delete contents of /home/pi/media from pi Player and try again?

**Comment by Rworld-Ravi** [comment]
I have tried everything. But no success. Can you tell me whats is "Range" here?

**Comment by colloqi** [comment]
wget uses incremental download, the range of bytes requested does not exist in the server.

**Comment by Rworld-Ravi** [comment]
Problem might have been cause of new versions of Mongodb and Node. Removed the latest versions of Mongodb and node and used mongodb 2.6.11 and Node 0.12.7 . Working perfact now.

**Comment by navaneetharaopy** [comment]
Hi, 
    Next time follow below steps:
1) ssh to raspberry pi and delete all files in `media` directory `rm -rf /home/pi/media/*`
2) Delete _config.json and _settings.json from `config` folder 
                `rm -rf /home/pi/piSignagePro/_config.json`
                `rm -rf /home/pi/piSignagePro/_settings.json`

3) reboot the pi

**Comment by Rworld-Ravi** [comment]
Hi Navaneetha
Thanks for the instructions.
I did the same, even a fresh install of pisignage player didn't worked. Finally I tried with past releases of Mongod and Nodejs, which got me out of problem.

**Comment by colloqi** [comment]
Hi Ravi,

I have added a fix which should solve the issue. V8 error object message had changed and server was sending 500 instead of 416. Thanks for your patience!

regards

**Comment by Rworld-Ravi** [comment]
Hi Colloqi

Thanks for the solution. Tried this with latest versions of MongoDB and Nodejs, works.
Even if someone faces the problem try the older versions of these, that solved the issue for me.

Thanks again.
