### ISSUE TITLE
Chown /data

### ISSUE THREAD

**Issue by rmscode** [colloqi/pisignage-server#193]
This part of the instructions are unclear to me. 

> NOTE: Please make sure mongod process is running and /data/db owenership is changed to regular user. If not use,  sudo chown -R your-username:user-group /data

`your-username:user-group /data` does not work because "user-group" is not a group . . . am I to use the "users" group or the group that is also the same name as my user?

**Comment by colloqi** [comment]
groups shell command in linux should list your group, if you are facing any issues in creating assets/groups, do not worry about this step

**Comment by rmscode** [comment]
Thanks for the clarification Ravi.
