### ISSUE TITLE
Chromecast with opensource-server

### ISSUE THREAD

**Issue by Raito00** [colloqi/pisignage-server#213]
Hello!
I try and Chromecast device Version 2 working nice with online pisignage.com

Question:
Can Chromecast device V2 connect to local opensource-server ?
Because i cant see option to change server address ...

**Comment by AbhijithBn** [comment]
Hi @Raito00 

If you are using Chromecast with **Google TV** support, you can install [piSignage for Android](https://play.google.com/store/apps/details?id=com.pisignage.player2&hl=en_IN). 

You can change the server from pisignage to your local server IP address following this article https://help.pisignage.com/hc/en-us/articles/14265849341081-Change-server-in-PiSignage-Android-2-0
