### ISSUE TITLE
Mongo version

### ISSUE THREAD

**Issue by timcanty** [colloqi/pisignage-server#217]
Has anybody attempted to use a newer mongodb version, 

Version 4.4 is really old and not supported, and the docker image and all the instructions suggest to only use mongodb 4.4, 
and just wondering if there was plans to support a newer version/anybody tried and had success using a newer version.

**Comment by hitesh83** [comment]
I am using it on 7.0.15

```
server:~$ mongod --version
db version v7.0.15
Build Info: {
    "version": "7.0.15",
    "gitVersion": "57939cc60865b0ce431c7e08c2589fa266a1a740",
    "openSSLVersion": "OpenSSL 3.0.2 15 Mar 2022",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "ubuntu2204",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}

```

**Comment by timcanty** [comment]
do you remember what you had to do to upgrade it from 4.4, think mongo you have to step through the versions, and do an upgrade on the database, but can't remember for sure.

**Comment by hitesh83** [comment]
No change to any part 

Did a fresh install on Ubuntu 22 LTS with node v18, mongo 7.
Restored old data using mongorestore cli.

**Comment by hitesh83** [comment]
![image](https://github.com/user-attachments/assets/ddca915d-64f1-4a4f-b641-b3a97d6f5acf)

Ubuntu 24.04, Mongo 8.0.3 node 18
(all fresh install)
