### ISSUE TITLE
server UI auth not happening after upgrade

### ISSUE THREAD

**Issue by harmane** [colloqi/pisignage-server#22]
Before updating to 0.9 I used htpasswd to create different logins for users. After updating, even with credentials set in settings I am never presented with a login dialog. These credentials set here work to access players and for players to auth to server.

Any ideas?

**Comment by colloqi** [comment]
Sorry for the delayed response, Is this the case even after closing he browser and reopening?

**Comment by harmane** [comment]
Now my turn to apologize for delayed response. :)

Yes, this is persistent throughout since the upgrade in any browser.

**Comment by harmane** [comment]
Figured it out...

`app.use(basicHttpAuth)`  was missing from express.js.

**Comment by colloqi** [comment]
👍 

Currently we have only one user support in this server. We also white-label pisignage.com server for an annual fee which has full user management support.

If the feature set is minimum please let us know and we will try to add it when resources permit.
