### ISSUE TITLE
Can't access server

### ISSUE THREAD

**Issue by squiggleuk** [colloqi/pisignage-server#23]
I've installed onto CentOS 6.7 as per instructions and got as far as 

"node server.js"

I see it download latest release, and it says #done. I can also see that it is listening on TCP port 3000 (I can also telnet to this port from another host.

There is never any response on port 3000 though. Borwser just hangs there.

I've never used mongoDB before... On CentOS, data dir seems to be in var, so I changed this to /data/db..... I can now see '/data/db/pisignage-dev.ns' files

Can we have server.js give more clues? or can anyone advise where I should look next?

**Comment by colloqi** [comment]
Do you see "Express server listening on port 3000 in development mode" message when you run node server.js (it is one of the first messages before player software download)

Is the browser you are using is Chrome? You could see if there are any errors in Chrome Inspector when you load the URL "http://localhost:3000"

**Comment by squiggleuk** [comment]
It wasn't displaying the line you mentioned - I was trying in Chrome, but zero response back!

However, I tried again this morning, and I get a response now!!! Bizzare!

Thanks for your reply - looking forward to having a play with this now :)
