### ISSUE TITLE
calendar asset

### ISSUE THREAD

**Issue by Rworld-Ravi** [colloqi/pisignage-server#24]
How to add the calendar asset? 

I have added my credentials in **'/config/env/all.js'**. and entered 'localhost:3000' as redirect_url. what is redirect_base_url? 
 in **'/public/app/templates/gcal-popup.html'** there is action **'api/gcal/authorize' which is not present** so  pointed the action to **'/app/controllers/gcal-authorize.js'**. But with no success. action always gives 404 error

**Comment by colloqi** [comment]
Sorry for the delayed response, I guess Google for redirect url needs other than localhost. Can you check hosting pisignage-server on a public url? Let me know if it still does not work, I will debug.

**Comment by Rworld-Ravi** [comment]
used ngrok to get a public url and tried with both default code and modified code but still same "404 not found". no success.

**Comment by colloqi** [comment]
This functionality has been removed, use direct link to calendar and it as webpage link
