### ISSUE TITLE
Scheduling playlist on series of days instead of individual days

### ISSUE THREAD

**Issue by starbuck93** [colloqi/pisignage-server#25]
Under the option to "You can select additional Playlists for Scheduling/Advt purposes", you are limited to 10 options, and mine have filled up very quickly. I would like an option to be able to have a rule extend over several days of the week instead of checking individual days similar to the Google Calendar "repeat" option found here:  [image link](http://imgur.com/a/ZlscC)

I need a playlist to play Sunday through Thursday, and a different one to run Friday and Saturday at various times on each one.

**Comment by colloqi** [comment]
Latest release(1.7.5) has the feature
