### ISSUE TITLE
Can not run server.js error

### ISSUE THREAD

**Issue by dinhkhaihtc** [colloqi/pisignage-server#30]
Can you help me? i run error

![image](https://cloud.githubusercontent.com/assets/12733966/19873586/7353a8de-9ff2-11e6-8d9d-861f70692363.png)

**Comment by navaneetharaopy** [comment]
Hi, looks like you have missed some modules . Run following commands
`npm cache clean`
`npm install`
 in pisignage-server directory.

**Comment by jcarpenter09** [comment]
My server runs fine for an hour or so, then stops. When attempting 'node server.js', I get the same error. Cannot get working until I do 'npm install'. Has happened about 4 times now.
