### ISSUE TITLE
Start server on boot?

### ISSUE THREAD

**Issue by JWise1203** [colloqi/pisignage-server#31]
What is the best method to start the server on boot?

**Comment by colloqi** [comment]
Depending on your OS, you can put the startup commands in sysvinit, Upstart or systemd. First you need to start mongod (for mongodb) and then node server.js. Also you need to give your working directory.

**Comment by JWise1203** [comment]
I am running Ubuntu and I am getting 'Permission Denied' when I try to execute the Upstart script. I have piSignage installed in:  /home/<adminuser>/pisignage-server/server.js

Here is the script I am using:

start on started mountall
stop on shutdown

respawn
respawn limit 99 5
console log

script

    chdir /home/<adminuser>/pisignage-server
    env NODE_ENV=production
    env PORT=3000
    exec /home/<adminuser>/pisignage-server/server.js

end script

**Comment by colloqi** [comment]
exec node /home/<adminuser>/pisignage-server/server.js
node is missing

**Comment by ADSPL** [comment]
I use pm2 start server.js
with crontab @reboot parameter

**Comment by colloqi** [comment]
https://github.com/colloqi/pisignage-server/blob/master/Init%20service%20example%20for%20systemd.md
