### ISSUE TITLE
Add player manually to pisignage-server

### ISSUE THREAD

**Issue by manuelsousa7** [colloqi/pisignage-server#51]
I have created a pisignage-sever inside a virtual machine (running inside OpenStack infrastructure) that has its own private ip private subnet. 
Then I have 1 raspberry pi installed with the latest player version, with a private ip address from a VLAN I specifically created for this situation. In order to establish communication between these devices I created firewall rules inside my routers, and both server and RPi can talk to each other. As obvious the server wont detect the RPi, so there is some way to add the player to the server?

**Comment by ADSPL** [comment]
1- confirm that player can communicate to server on given port
2- make sure server ip is configured properly in player. Confirm by going to player Ip in your browser with port no 8000.

There is no player add button, as soon as server and player start communicating with each other, player will be shown in server automatically.

**Comment by colloqi** [comment]
Also make sure
-  your server address is given as pisignage-server-ip:3000
- port 3000 is open in the firewall

**Comment by manuelsousa7** [comment]
thank you. I was missing the port in raspberry
