### ISSUE TITLE
HTTP Stream always failing

### ISSUE THREAD

**Issue by manuelsousa7** [colloqi/pisignage-server#52]
I have a local http stream, that is running fine in other raspbery pi's that are currently using Kodi. I am now trying using pisignage, which will use omxplayer. Where can i change omxplayer settings/flags in order to improve stream quality? Do you now tips about this?

**Comment by colloqi** [comment]
Sorry for the delayed reply, they are selected as command line options which is part of the player code. Are you looking for any specific flags?

**Comment by manuelsousa7** [comment]
Upgraded, is now working properly
