### ISSUE TITLE
Deprecation warnings and defective server restart on Windows

### ISSUE THREAD

**Issue by jtlarson** [colloqi/pisignage-server#53]
Trying to modify the "username at pisignage.com" field causes the server.js proces to fail on Windows, with the following errors:
`(node:3164) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
express deprecated req.param(name): Use req.params, req.body, or req.query instead app\controllers\groups.js:74:13
express deprecated req.param(name): Use req.params, req.body, or req.query instead app\controllers\players.js:203:13
express deprecated req.param(name): Use req.params, req.body, or req.query instead app\controllers\players.js:207:13
restarting server
`
also
`(node:3512) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
restarting server`

**Comment by firestorms321** [comment]
Same error here : #Done
(node:7964) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
express deprecated req.param(name): Use req.params, req.body, or req.query instead app\controllers\groups.js:74:13
express deprecated req.param(name): Use req.params, req.body, or req.query instead app\controllers\players.js:206:13
express deprecated req.param(name): Use req.params, req.body, or req.query instead app\controllers\players.js:210:13
restarting server

i'm on the latest version of node
