### ISSUE TITLE
Player behind HTTP proxy

### ISSUE THREAD

**Issue by lewebsimple** [colloqi/pisignage-server#58]
Our client has one of their players behind an HTTP proxy, which was configured on raspbian based on the answer [here](https://raspberrypi.stackexchange.com/questions/68580/how-do-i-set-proxy-in-raspberry-pi-raspbian-os-or-any-linux-using-command-li/68583).

This player is not seen by the server and doesn't receive updates.

Is there anything I'm missing for this setup to work ?

**Comment by colloqi** [comment]
The player uses websocket traffic to communicate to server, is the same enabled in proxy. open source server uses port 3000 to communicate, does the proxy take care of forwarding port 3000 traffic?

**Comment by lewebsimple** [comment]
The server maps traffic on port 80 to port 3000 internally using nginx on the docker container.
Is there a delay for the player to show up as connected on the web interface of the server?
Thanks a lot!

**Comment by lewebsimple** [comment]
Is it also possible that the network request is being done directly by the player software and is not using the raspberry pi's http_proxy setting? In that case, it would require a new feature in the player settings, i.e. proxy settings.

**Comment by colloqi** [comment]
player software always uses OS setting and that way you have more flexibility and not dependent on us for standard features
