### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by hitesh83** [colloqi/pisignage-server#60]
```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b 0.9.x https://github.com/colloqi/socket.io.git /home/a                                                      dspl/.npm/_cacache/tmp/git-clone-e1818b9d
npm ERR! /home/adspl/.npm/_cacache/tmp/git-clone-e1818b9d/.git: Permission denied
npm ERR!

```
switching from deprecated-dialogue to master branch using git checkout,
Did git pull origin master
then npm install, 
gives above error

switch backed to deprecated-dialogue brach and did npm install, server working.

**Comment by colloqi** [comment]
it is something to do with npm cache looking at the ERR. 

Can you uninstall 919.socket.io npm package, npm cache clean and try installing again?

**Comment by hitesh83** [comment]
My node setup was messed up,
removed old version and installed thru below command.
Now working
```
curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
sudo apt-get install -y nodejs
```
