### ISSUE TITLE
Cannot start server because of db.connection.on error

### ISSUE THREAD

**Issue by jphoubion** [colloqi/pisignage-server#61]
Hi!
I would like to try pisignage server, but when I start it with "node server.js", I've got the following error msg.
![pisignage](https://user-images.githubusercontent.com/25503721/47955221-ce0e5600-df94-11e8-9eea-2c56cfd87440.png)

Could you tell me what happend?

Thanks for your help

**Comment by colloqi** [comment]
Make sure mongod is running and url is correct in config/env/development.js

**Comment by jphoubion** [comment]
Hi,
Here is the result of `sudo service mongod status`

_jp@jp-vbox:~/pisignage-server$ sudo service mongod status
● mongod.service - MongoDB Database Server
   Loaded: loaded (/lib/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-11-05 12:57:08 CET; 7min ago
     Docs: https://docs.mongodb.org/manual
 Main PID: 5257 (mongod)
   CGroup: /system.slice/mongod.service
           └─5257 /usr/bin/mongod --config /etc/mongod.conf

nov 05 12:57:08 jp-vbox systemd[1]: Started MongoDB Database Server.
nov 05 12:57:08 jp-vbox mongod[5257]: 2018-11-05T12:57:08.535+0100 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'_

And here is the content of the development.js file

_'use strict';

module.exports = {
    env: 'development',
    https: false,
    port: process.env.PORT || 3000,
    mongo: {
        uri: 'mongodb://localhost/pisignage-server-dev'
    }
};_

I don't know what is wrong :-/

Thanks for your help

**Comment by shihabulmilah** [comment]
Hi jphoubion, 

Have you solve this issue? I got the same problem

Thanks

**Comment by jphoubion** [comment]
Hi shihabulmilah ,
Unfortunatly no, so i gave up for the moment.
I was waiting for an answer from the developer.

**Comment by shihabulmilah** [comment]
I'm waiting too :D

**Comment by colloqi** [comment]
Hello,

The error is because mongodb connection is not going through and db variable is not valid. in server.js can you change the line 

mongoose.connect(config.mongo.uri, config.mongo.options); 

to have an error callback as shown and see what error is thrown?

mongoose.connect(config.mongo.uri, config.mongo.options, function(err) {
    if (err) 
        console.log(err);
});

**Comment by shihabulmilah** [comment]
Hi colloqi,

I have tried but still not working, got same error

Thanks

**Comment by shihabulmilah** [comment]
Okay, that possible remote and check my server, send email to support@pisignage.com?

**Comment by colloqi** [comment]
Yes

**Comment by colloqi** [comment]
in config/env/ directory, can you replace "localhost" with 127.0.0.1:27017 in files development.js, production.js and try?  The error could be due to DNS failure

**Comment by Rathius** [comment]
Might want to take a look at this https://github.com/Automattic/mongoose/issues/5399

**Comment by colloqi** [comment]
More specifically https://github.com/Automattic/mongoose/issues/5399#issuecomment-322041860
