### ISSUE TITLE
Cannot Find Module '919.socket.io'

### ISSUE THREAD

**Issue by shihabulmilah** [colloqi/pisignage-server#66]
Hi All

Somebody can help me please,

![image](https://user-images.githubusercontent.com/46400709/50725632-c1dc7b80-1132-11e9-8772-2f2f4ab5ca9c.png)

Thanks

**Comment by dbmello75** [comment]
Hello, I trying to install in Debian 10, no sucess. 

```
npm info lifecycle 919.socket.io@0.9.19~prepack: 919.socket.io@0.9.19
Illegal instruction] / fetchMetadata: info lifecycle 919.socket.io@0.9.19~prepack: 919.socket.io@0.9.19

```
