### ISSUE TITLE
[Bug] Unable to upload video to pisignage-server

### ISSUE THREAD

**Issue by zacharydonsky** [colloqi/pisignage-server#72]
Cannot upload mp4 video to pisignage-server. 

**Machine Specs**
```
Ubuntu 16.04
mongod v2.6.10
node v8.16.0
npm 6.4.1
```

**Error from PiSignage**
```
ffmpeg, An error occurred: ffmpeg exited with code 1: /root/media/video.mp4: No such file or directory

store details(media processing) error messages: video.mp4
ffmpeg exited with code 1: /root/media/video: No such file or directory
```

The directory /root/media does exist, and image uploads to that location work fine.

**Comment by colloqi** [comment]
Hi

Are there any permission issues as it reports video.mp4 does not exist.

**Comment by bigpappa456** [comment]
Did some found a solution for this

**Comment by colloqi** [comment]
Closing as there is no feedback
