### ISSUE TITLE
Problem local server windows 

### ISSUE THREAD

**Issue by matrixsx** [colloqi/pisignage-server#74]
5 Jul 14:29:11 - info: *** sync initiated at server: 7/5/2019, 2:29:07 PM
5 Jul 14:29:12 - info: Spawning wget -rNnHd,--no-parent,-t,20,--waitretry,60,--retry-connrefused,--no-cache,-R,default,10.38.34.160:3000/sync_folders/local/default; Running as PID 2383
5 Jul 14:29:12 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:13 - info: wget stopped with code 0 and signal null; downloadInProgressCount: 1
5 Jul 14:29:13 - info: COPIED SERVER FILES default SUCCESSFULLY.
5 Jul 14:29:17 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:19 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:20 - info: *** Changing Playlist *** to test
5 Jul 14:29:20 - info: Change playlist,deleting files: default.tmp
5 Jul 14:29:22 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:24 - info: Chrome loaded page /home/pi/piSignagePro/templates/2a.html;?1562318959906
5 Jul 14:29:24 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:27 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:30 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:32 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:35 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:37 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:40 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:43 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:45 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:48 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:50 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:53 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:55 - error: Playlist duration is less than 1 second, delaying for a second
5 Jul 14:29:58 - error: Playlist duration is less than 1 second, delaying for a second

**Comment by colloqi** [comment]
- Please set your user name same as that of pisignage.com (instead of local)
- Did you deploy after playlist is assigned to Group and reboot the player if needed
