### ISSUE TITLE
Bug: Drag'n'Drop while assigning assets with filter by label

### ISSUE THREAD

**Issue by staegi** [colloqi/pisignage-server#78]
If you try to drag and drop an asset to a playlist and a label filter is set then a wrong file is assigned. This happens only when some assets are filtered out above the dragged asset.

**Comment by hitesh83** [comment]
This was fixed long time back, you are on which version / release date ?

**Comment by staegi** [comment]
I use release 2.5.4: https://hub.docker.com/r/tomcat2111/pisignage-server/dockerfile

**Comment by hitesh83** [comment]
is you issue same as this https://github.com/colloqi/pisignage-server/issues/43

**Comment by hitesh83** [comment]
using below branch mention in docker, I am not able to reproduce your issue.
> git clone --branch 2.5.4 https://github.com/colloqi/pisignage-server

**Comment by staegi** [comment]
You are right. In this version it works.
