### ISSUE TITLE
sizing video and layout + playing sound

### ISSUE THREAD

**Issue by youbloub** [colloqi/pisignage-server#82]
hello,
how to make custom layout, or can I modify preselected to fit for something that's good for me ?
Can videos auto fit without be streched ?
when I put a mp3, sound stop even if I put 120s under playlist.

**Comment by hitesh83** [comment]
Yes, you can make custom layout.
Video will auto fit by giving video dimensions in layout but it will get stretch if not in exact dimensions of layout. Stretch is nothing to do with Pisignage,
