### ISSUE TITLE
Need https

### ISSUE THREAD

**Issue by bigpappa456** [colloqi/pisignage-server#87]
I have set up the pi signage server on a VPS, i can get https to port 443 when i install webserver on the machine, but when i go to port 3000 allways the connection is http, anyone know how to make it https on the node on port 3000?

**Comment by hitesh83** [comment]
Simplest way is to use reverse proxy of nginx . 
Using same from last 2 years 

Ref- https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

**Comment by bigpappa456** [comment]
> Simplest way is to use reverse proxy of nginx .
> Using same from last 2 years
> 
> Ref- https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins
> 
> https://medium.com/@mightywomble/how-to-set-up-nginx-reverse-proxy-with-lets-encrypt-8ef3fd6b79e5

I tried this but i did not get it to work, is there some how a way you can help me with this??

**Comment by hitesh83** [comment]
If I can ssh to your server it can be done in 30min. Also if you have any sub domain or domain directing to VPS ip that will help in opening in browser rather than with IP.

**Comment by bigpappa456** [comment]
If you could help me it would be great i am creating subs by using dns on the vps, i create a New server for New customers  and place the snapshot on it but the domain Will be always the same how can i send you the credentials so you could help me if you want.

**Comment by hitesh83** [comment]
How about starting with mail, 
Mail me on hitesh@hambarde.com

**Comment by bigpappa456** [comment]
I send you an email from Gmail account

**Comment by colloqi** [comment]
Closing this issue, if https is needed server.js can be modified accordingly (code exists but need to be modified for certificate locations and config need to be updated).

**Comment by saintofinternet** [comment]
> 
> 
> I have set up the pi signage server on a VPS, i can get https to port 443 when i install webserver on the machine, but when i go to port 3000 allways the connection is http, anyone know how to make it https on the node on port 3000?

have you installed the PiSignage on a DigitalOcean Droplet? 

would be really helpful if you could guide me on it too please!!!

**Comment by hitesh83** [comment]
> > I have set up the pi signage server on a VPS, i can get https to port 443 when i install webserver on the machine, but when i go to port 3000 allways the connection is http, anyone know how to make it https on the node on port 3000?
> 
> have you installed the PiSignage on a DigitalOcean Droplet?
> 
> would be really helpful if you could guide me on it too please!!!

It is the same as installing on your local server, no special modifications are required.
