### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by bigpappa456** [colloqi/pisignage-server#90]
Is there also an other way to upload assets, maybe thrue ftp so that they are visible in the assets list

**Comment by colloqi** [comment]
The assets are stored in ../media directory of the server (same level as pisignage-server directory). You could directly copy the assets to that folder. However following things won't happen
1. Thumbnails
2. video conversion to mp4 or reducing the resolution to fit
3. image resolution reduction if needed
4. Asset details

**Comment by bigpappa456** [comment]
Ok so that is no solution to bad, than i need to login to the server an upload it thru the button

  Op 7 mei 2020 om 14:27 schreef Ravi Bail Bhat <notifications@github.com>:
 
 
  
 The assets are stored in ../media directory of the server (same level as pisignage-server directory). You could directly copy the assets to that folder. However following things won't happen 
  
  Thumbnails 
  video conversion to mp4 or reducing the resolution to fit 
  image resolution reduction if needed 
  Asset details

**Comment by bigpappa456** [comment]
Is there a trigger to do this manualy, so that a scan will start on the media folder and that the above will be created?

**Comment by colloqi** [comment]
You could rely on external Linux/Windows programs like rsync,scp,ftp etc.
